logging:
  level:
    root: WARN
    com.example.demo1: WARN
    org.springframework.web: WARN

server:
  error:
    include-stacktrace: never


#  Summary â€” Endpoints you get with *
#  Category	Endpoints
#  Core	health, info
#  Config & Environment	env, beans, configprops, conditions, mappings, loggers
#  Monitoring	metrics, metrics/*, prometheus
#  Debugging	threaddump, heapdump, httpexchanges
#  Integrations	flyway, liquibase, caches, quartz, etc.
#  Optional	shutdown

management:
  endpoints:
    web:
      exposure:
        include: conditions, beans, health, metrics
  metics:
    enable:
      http.server.requests: true
  endpoint:
    heap dump:
      enabled: true