spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo1
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/demo1
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: DEBUG
    com.example.demo1: DEBUG
    org.springframework.web: DEBUG

#  Summary â€” Endpoints you get with *
#  Category	Endpoints
#  Core	health, info
#  Config & Environment	env, beans, configprops, conditions, mappings, loggers
#  Monitoring	metrics, metrics/*, prometheus
#  Debugging	threaddump, heapdump, httpexchanges
#  Integrations	flyway, liquibase, caches, quartz, etc.
#  Optional	shutdown

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    heap dump:
      enabled: true



